- name: Install arc theme
  apt: name=arc-theme

- name: create ~/.themes folder
  file:
    path: /home/zanedufour/.themes
    state: directory

- name: create ~/.icons folder
  file:
    path: /home/zanedufour/.icons
    state: directory

- name: Install psutil package
  apt: name=python3-psutil

- name: Copy wallpaper file
  copy: src=files/wallpaper.jpg dest=/home/zanedufour/.wallpaper.jpg owner=zanedufour group=zanedufour mode=600

- name: Set GNOME wallpaper
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/background/picture-uri" value="'file:///home/zanedufour/.wallpaper.jpg'"

- name: Copy lockscreenfile
  become_user: zanedufour
  copy: src=files/lockscreen.jpg dest=/home/zanedufour/.lockscreen.jpg owner=zanedufour group=zanedufour mode=600

- name: Set lock screen background
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/screensaver/picture-uri" value="'file:///home/zanedufour/.lockscreen.jpg'"

- name: Set GTK theme
  become_user: zanedufour
  dconf: key="/org/gnome/desktop/interface/gtk-theme" value="'Pop-dark'"

- name: install dash-to-dock
  copy:
    src: files/dash-to-dock/
    dest: "/home/{{ user }}/.local/share/gnome-shell/extensions/dash-to-dock@micxgx.gmail.com/"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: u=rw,g=r,o=r
  loop:
    - zanedufour
    - zdufour
  loop_control:
    loop_var: user

- name: dconf settings
  vars:
    settings:
      - {key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme", val: "true"}
      - {key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed", val: "true"}
      - {key: "/org/gnome/shell/extensions/dash-to-dock/extend-height", val: "true"}
      - {key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor", val: "true"}
      - {key: "/org/gnome/shell/extensions/dash-to-dock/show-trash", val: "false"}
      - {
        key: "/org/gnome/shell/favorite-apps",
        val: "[
          'brave-browser.desktop',
          'code.desktop',
          'org.gnome.Terminal.desktop',
          'thunderbird.desktop'
          ]"
      }
      - {
        key: "/org/gnome/desktop/wm/preferences/button-layout",
        val: "'appmenu:minimize,maximize,close'"
      }
  become_user: "{{ item.0 }}"
  community.general.dconf:
    key: "{{ item.1.key }}"
    value: "{{ item.1.val }}"
  with_nested:
    - "{{ personal_users }}"
    - "{{ settings }}"

- name: Turn on gnome extensions
  become_user: "{{ user }}"
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "[
      'alt-tab-raise-first-window@system76.com',
      'always-show-workspaces@system76.com',
      'batteryiconfix@kylecorry31.github.io',
      'desktop-icons@csoriano',
      'pop-shell@system76.com',
      'pop-shop-details@system76.com',
      'system76-power@system76.com',
      'ubuntu-appindicators@ubuntu.com',
      'dash-to-dock@micxgx.gmail.com'
      ]"
    state: present
  loop:
    - zanedufour
    - zdufour
  loop_control:
    loop_var: user