- name: install nvm
  shell: "
    NVM_DIR=/home/{{ user }} \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.36.0/install.sh | bash
  "
  args:
    creates: "/home/{{ user }}/.nvm"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control: 
    loop_var: user

- name: install node with nvm
  shell: bash -ilc "nvm install 12.18.3 --default --latest-npm"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control: 
    loop_var: user

- name: set node version with nvm
  shell: bash -ilc "nvm alias default 12.18.3"
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user

- name: remove nvm use from .bashrc
  lineinfile:
    path: "/home/{{ user }}/.bashrc"
    regexp: "nvm use \d{1,2}\\.\d{1,2}\\.\d{1,2}.*"
    # line: "nvm use 12.18.3 > /dev/null"
    state: absent
  become_user: "{{ user }}"
  loop: "{{ personal_users }}"
  loop_control:
    loop_var: user

- name: install global node packages
  shell: bash -ilc "npm install {{ item.1 }}"
  become_user: "{{ item.0 }}"
  args:
    creates: "/home/{{ item.0 }}/.nvm/versions/node/v12.18.3/bin/{{item.1}}"
  with_nested:
    - "{{ personal_users }}"
    - ['nativefier']
